// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.3
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _bypass_HH_
#define _bypass_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "bypass_AXILiteS_s_axi.h"
#include "bypass_physMemPtr_V_m_axi.h"

namespace ap_rtl {

template<unsigned int C_M_AXI_PHYSMEMPTR_V_ADDR_WIDTH = 32,
         unsigned int C_M_AXI_PHYSMEMPTR_V_ID_WIDTH = 1,
         unsigned int C_M_AXI_PHYSMEMPTR_V_AWUSER_WIDTH = 1,
         unsigned int C_M_AXI_PHYSMEMPTR_V_DATA_WIDTH = 32,
         unsigned int C_M_AXI_PHYSMEMPTR_V_WUSER_WIDTH = 1,
         unsigned int C_M_AXI_PHYSMEMPTR_V_ARUSER_WIDTH = 1,
         unsigned int C_M_AXI_PHYSMEMPTR_V_RUSER_WIDTH = 1,
         unsigned int C_M_AXI_PHYSMEMPTR_V_BUSER_WIDTH = 1,
         unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 5,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct bypass : public sc_module {
    // Port declarations 65
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > m_axi_physMemPtr_V_AWVALID;
    sc_in< sc_logic > m_axi_physMemPtr_V_AWREADY;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_ADDR_WIDTH> > m_axi_physMemPtr_V_AWADDR;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_ID_WIDTH> > m_axi_physMemPtr_V_AWID;
    sc_out< sc_lv<8> > m_axi_physMemPtr_V_AWLEN;
    sc_out< sc_lv<3> > m_axi_physMemPtr_V_AWSIZE;
    sc_out< sc_lv<2> > m_axi_physMemPtr_V_AWBURST;
    sc_out< sc_lv<2> > m_axi_physMemPtr_V_AWLOCK;
    sc_out< sc_lv<4> > m_axi_physMemPtr_V_AWCACHE;
    sc_out< sc_lv<3> > m_axi_physMemPtr_V_AWPROT;
    sc_out< sc_lv<4> > m_axi_physMemPtr_V_AWQOS;
    sc_out< sc_lv<4> > m_axi_physMemPtr_V_AWREGION;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_AWUSER_WIDTH> > m_axi_physMemPtr_V_AWUSER;
    sc_out< sc_logic > m_axi_physMemPtr_V_WVALID;
    sc_in< sc_logic > m_axi_physMemPtr_V_WREADY;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_DATA_WIDTH> > m_axi_physMemPtr_V_WDATA;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_DATA_WIDTH/8> > m_axi_physMemPtr_V_WSTRB;
    sc_out< sc_logic > m_axi_physMemPtr_V_WLAST;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_ID_WIDTH> > m_axi_physMemPtr_V_WID;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_WUSER_WIDTH> > m_axi_physMemPtr_V_WUSER;
    sc_out< sc_logic > m_axi_physMemPtr_V_ARVALID;
    sc_in< sc_logic > m_axi_physMemPtr_V_ARREADY;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_ADDR_WIDTH> > m_axi_physMemPtr_V_ARADDR;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_ID_WIDTH> > m_axi_physMemPtr_V_ARID;
    sc_out< sc_lv<8> > m_axi_physMemPtr_V_ARLEN;
    sc_out< sc_lv<3> > m_axi_physMemPtr_V_ARSIZE;
    sc_out< sc_lv<2> > m_axi_physMemPtr_V_ARBURST;
    sc_out< sc_lv<2> > m_axi_physMemPtr_V_ARLOCK;
    sc_out< sc_lv<4> > m_axi_physMemPtr_V_ARCACHE;
    sc_out< sc_lv<3> > m_axi_physMemPtr_V_ARPROT;
    sc_out< sc_lv<4> > m_axi_physMemPtr_V_ARQOS;
    sc_out< sc_lv<4> > m_axi_physMemPtr_V_ARREGION;
    sc_out< sc_uint<C_M_AXI_PHYSMEMPTR_V_ARUSER_WIDTH> > m_axi_physMemPtr_V_ARUSER;
    sc_in< sc_logic > m_axi_physMemPtr_V_RVALID;
    sc_out< sc_logic > m_axi_physMemPtr_V_RREADY;
    sc_in< sc_uint<C_M_AXI_PHYSMEMPTR_V_DATA_WIDTH> > m_axi_physMemPtr_V_RDATA;
    sc_in< sc_logic > m_axi_physMemPtr_V_RLAST;
    sc_in< sc_uint<C_M_AXI_PHYSMEMPTR_V_ID_WIDTH> > m_axi_physMemPtr_V_RID;
    sc_in< sc_uint<C_M_AXI_PHYSMEMPTR_V_RUSER_WIDTH> > m_axi_physMemPtr_V_RUSER;
    sc_in< sc_lv<2> > m_axi_physMemPtr_V_RRESP;
    sc_in< sc_logic > m_axi_physMemPtr_V_BVALID;
    sc_out< sc_logic > m_axi_physMemPtr_V_BREADY;
    sc_in< sc_lv<2> > m_axi_physMemPtr_V_BRESP;
    sc_in< sc_uint<C_M_AXI_PHYSMEMPTR_V_ID_WIDTH> > m_axi_physMemPtr_V_BID;
    sc_in< sc_uint<C_M_AXI_PHYSMEMPTR_V_BUSER_WIDTH> > m_axi_physMemPtr_V_BUSER;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_logic > ap_var_for_const6;
    sc_signal< sc_lv<1> > ap_var_for_const1;
    sc_signal< sc_lv<3> > ap_var_for_const2;
    sc_signal< sc_lv<2> > ap_var_for_const3;
    sc_signal< sc_lv<4> > ap_var_for_const4;
    sc_signal< sc_lv<32> > ap_var_for_const5;
    sc_signal< sc_lv<4> > ap_var_for_const7;


    // Module declarations
    bypass(sc_module_name name);
    SC_HAS_PROCESS(bypass);

    ~bypass();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    bypass_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* bypass_AXILiteS_s_axi_U;
    bypass_physMemPtr_V_m_axi<0,32,32,5,16,16,16,16,C_M_AXI_PHYSMEMPTR_V_ID_WIDTH,C_M_AXI_PHYSMEMPTR_V_ADDR_WIDTH,C_M_AXI_PHYSMEMPTR_V_DATA_WIDTH,C_M_AXI_PHYSMEMPTR_V_AWUSER_WIDTH,C_M_AXI_PHYSMEMPTR_V_ARUSER_WIDTH,C_M_AXI_PHYSMEMPTR_V_WUSER_WIDTH,C_M_AXI_PHYSMEMPTR_V_RUSER_WIDTH,C_M_AXI_PHYSMEMPTR_V_BUSER_WIDTH,C_M_AXI_PHYSMEMPTR_V_TARGET_ADDR,C_M_AXI_PHYSMEMPTR_V_USER_VALUE,C_M_AXI_PHYSMEMPTR_V_PROT_VALUE,C_M_AXI_PHYSMEMPTR_V_CACHE_VALUE>* bypass_physMemPtr_V_m_axi_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<24> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > basePhysAddr_V;
    sc_signal< sc_logic > physMemPtr_V_blk_n_AR;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > physMemPtr_V_blk_n_R;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > icmp_ln23_fu_142_p2;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_logic > physMemPtr_V_blk_n_AW;
    sc_signal< sc_logic > physMemPtr_V_blk_n_W;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_logic > physMemPtr_V_blk_n_B;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<1> > icmp_ln23_reg_198;
    sc_signal< sc_logic > physMemPtr_V_AWVALID;
    sc_signal< sc_logic > physMemPtr_V_AWREADY;
    sc_signal< sc_lv<32> > physMemPtr_V_AWADDR;
    sc_signal< sc_logic > physMemPtr_V_WVALID;
    sc_signal< sc_logic > physMemPtr_V_WREADY;
    sc_signal< sc_logic > physMemPtr_V_ARVALID;
    sc_signal< sc_logic > physMemPtr_V_ARREADY;
    sc_signal< sc_lv<32> > physMemPtr_V_ARADDR;
    sc_signal< sc_lv<32> > physMemPtr_V_ARLEN;
    sc_signal< sc_logic > physMemPtr_V_RVALID;
    sc_signal< sc_logic > physMemPtr_V_RREADY;
    sc_signal< sc_lv<32> > physMemPtr_V_RDATA;
    sc_signal< sc_logic > physMemPtr_V_RLAST;
    sc_signal< sc_lv<1> > physMemPtr_V_RID;
    sc_signal< sc_lv<1> > physMemPtr_V_RUSER;
    sc_signal< sc_lv<2> > physMemPtr_V_RRESP;
    sc_signal< sc_logic > physMemPtr_V_BVALID;
    sc_signal< sc_logic > physMemPtr_V_BREADY;
    sc_signal< sc_lv<2> > physMemPtr_V_BRESP;
    sc_signal< sc_lv<1> > physMemPtr_V_BID;
    sc_signal< sc_lv<1> > physMemPtr_V_BUSER;
    sc_signal< sc_lv<32> > reg_106;
    sc_signal< sc_lv<30> > r_V_fu_112_p4;
    sc_signal< sc_lv<30> > r_V_reg_172;
    sc_signal< sc_lv<31> > zext_ln215_fu_122_p1;
    sc_signal< sc_lv<31> > zext_ln215_reg_177;
    sc_signal< sc_lv<31> > ret_V_fu_126_p2;
    sc_signal< sc_lv<31> > ret_V_reg_182;
    sc_signal< sc_lv<32> > status_V_reg_193;
    sc_signal< bool > ap_block_state10_io;
    sc_signal< sc_lv<31> > ret_V_1_fu_157_p2;
    sc_signal< sc_lv<31> > ret_V_1_reg_208;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<64> > zext_ln544_fu_132_p1;
    sc_signal< sc_lv<64> > zext_ln544_1_fu_147_p1;
    sc_signal< sc_lv<64> > zext_ln544_2_fu_162_p1;
    sc_signal< bool > ap_block_state24;
    sc_signal< sc_lv<24> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<24> ap_ST_fsm_state1;
    static const sc_lv<24> ap_ST_fsm_state2;
    static const sc_lv<24> ap_ST_fsm_state3;
    static const sc_lv<24> ap_ST_fsm_state4;
    static const sc_lv<24> ap_ST_fsm_state5;
    static const sc_lv<24> ap_ST_fsm_state6;
    static const sc_lv<24> ap_ST_fsm_state7;
    static const sc_lv<24> ap_ST_fsm_state8;
    static const sc_lv<24> ap_ST_fsm_state9;
    static const sc_lv<24> ap_ST_fsm_state10;
    static const sc_lv<24> ap_ST_fsm_state11;
    static const sc_lv<24> ap_ST_fsm_state12;
    static const sc_lv<24> ap_ST_fsm_state13;
    static const sc_lv<24> ap_ST_fsm_state14;
    static const sc_lv<24> ap_ST_fsm_state15;
    static const sc_lv<24> ap_ST_fsm_state16;
    static const sc_lv<24> ap_ST_fsm_state17;
    static const sc_lv<24> ap_ST_fsm_state18;
    static const sc_lv<24> ap_ST_fsm_state19;
    static const sc_lv<24> ap_ST_fsm_state20;
    static const sc_lv<24> ap_ST_fsm_state21;
    static const sc_lv<24> ap_ST_fsm_state22;
    static const sc_lv<24> ap_ST_fsm_state23;
    static const sc_lv<24> ap_ST_fsm_state24;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_17;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_M_AXI_PHYSMEMPTR_V_TARGET_ADDR;
    static const int C_M_AXI_PHYSMEMPTR_V_USER_VALUE;
    static const int C_M_AXI_PHYSMEMPTR_V_PROT_VALUE;
    static const int C_M_AXI_PHYSMEMPTR_V_CACHE_VALUE;
    static const int C_M_AXI_DATA_WIDTH;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<31> ap_const_lv31_4;
    static const sc_lv<31> ap_const_lv31_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const6();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const5();
    void thread_ap_var_for_const7();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state10_io();
    void thread_ap_block_state24();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_icmp_ln23_fu_142_p2();
    void thread_physMemPtr_V_ARADDR();
    void thread_physMemPtr_V_ARLEN();
    void thread_physMemPtr_V_ARVALID();
    void thread_physMemPtr_V_AWADDR();
    void thread_physMemPtr_V_AWVALID();
    void thread_physMemPtr_V_BREADY();
    void thread_physMemPtr_V_RREADY();
    void thread_physMemPtr_V_WVALID();
    void thread_physMemPtr_V_blk_n_AR();
    void thread_physMemPtr_V_blk_n_AW();
    void thread_physMemPtr_V_blk_n_B();
    void thread_physMemPtr_V_blk_n_R();
    void thread_physMemPtr_V_blk_n_W();
    void thread_r_V_fu_112_p4();
    void thread_ret_V_1_fu_157_p2();
    void thread_ret_V_fu_126_p2();
    void thread_zext_ln215_fu_122_p1();
    void thread_zext_ln544_1_fu_147_p1();
    void thread_zext_ln544_2_fu_162_p1();
    void thread_zext_ln544_fu_132_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
