// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1.3
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _effect_compressor_HH_
#define _effect_compressor_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "pynq_dsp_hls_faddfYi.h"
#include "pynq_dsp_hls_fmulcud.h"
#include "pynq_dsp_hls_fcmpeOg.h"

namespace ap_rtl {

struct effect_compressor : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > inData_l;
    sc_in< sc_lv<32> > inData_r;
    sc_out< sc_lv<8> > config_r_address0;
    sc_out< sc_logic > config_r_ce0;
    sc_in< sc_lv<32> > config_r_q0;
    sc_in< sc_lv<5> > config_offset;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<5> > ap_var_for_const1;


    // Module declarations
    effect_compressor(sc_module_name name);
    SC_HAS_PROCESS(effect_compressor);

    ~effect_compressor();

    sc_trace_file* mVcdFile;

    pynq_dsp_hls_faddfYi<1,7,32,32,32>* pynq_dsp_hls_faddfYi_U30;
    pynq_dsp_hls_faddfYi<1,7,32,32,32>* pynq_dsp_hls_faddfYi_U31;
    pynq_dsp_hls_fmulcud<1,4,32,32,32>* pynq_dsp_hls_fmulcud_U32;
    pynq_dsp_hls_fmulcud<1,4,32,32,32>* pynq_dsp_hls_fmulcud_U33;
    pynq_dsp_hls_fcmpeOg<1,2,32,32,1>* pynq_dsp_hls_fcmpeOg_U34;
    pynq_dsp_hls_fcmpeOg<1,2,32,32,1>* pynq_dsp_hls_fcmpeOg_U35;
    sc_signal< sc_lv<23> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > grp_fu_95_p2;
    sc_signal< sc_lv<32> > reg_121;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<1> > and_ln24_1_reg_525;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<32> > grp_fu_99_p2;
    sc_signal< sc_lv<32> > reg_126;
    sc_signal< sc_lv<1> > and_ln31_1_reg_531;
    sc_signal< sc_lv<9> > tmp_43_fu_131_p3;
    sc_signal< sc_lv<9> > tmp_43_reg_458;
    sc_signal< sc_lv<31> > trunc_ln368_fu_154_p1;
    sc_signal< sc_lv<31> > trunc_ln368_reg_468;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > or_ln24_1_fu_184_p2;
    sc_signal< sc_lv<1> > or_ln24_1_reg_473;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > thresh_fu_197_p1;
    sc_signal< sc_lv<32> > thresh_reg_491;
    sc_signal< sc_lv<32> > absL_fu_223_p1;
    sc_signal< sc_lv<32> > absL_reg_501;
    sc_signal< sc_lv<32> > absR_fu_248_p1;
    sc_signal< sc_lv<32> > absR_reg_507;
    sc_signal< sc_lv<1> > or_ln24_fu_275_p2;
    sc_signal< sc_lv<1> > or_ln24_reg_513;
    sc_signal< sc_lv<1> > or_ln31_fu_303_p2;
    sc_signal< sc_lv<1> > or_ln31_reg_519;
    sc_signal< sc_lv<1> > and_ln24_1_fu_313_p2;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > and_ln31_1_fu_323_p2;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<31> > trunc_ln368_4_fu_343_p1;
    sc_signal< sc_lv<31> > trunc_ln368_4_reg_542;
    sc_signal< sc_lv<32> > ratio_fu_354_p1;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<32> > grp_fu_103_p2;
    sc_signal< sc_lv<32> > tmp_22_reg_553;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<32> > grp_fu_107_p2;
    sc_signal< sc_lv<32> > tmp_26_reg_558;
    sc_signal< sc_lv<1> > grp_fu_111_p2;
    sc_signal< sc_lv<1> > tmp_34_reg_563;
    sc_signal< sc_lv<1> > grp_fu_115_p2;
    sc_signal< sc_lv<1> > tmp_39_reg_568;
    sc_signal< sc_lv<64> > tmp_44_fu_145_p3;
    sc_signal< sc_lv<64> > tmp_45_fu_334_p3;
    sc_signal< sc_lv<32> > grp_fu_95_p0;
    sc_signal< sc_lv<32> > grp_fu_95_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<32> > grp_fu_99_p0;
    sc_signal< sc_lv<32> > grp_fu_99_p1;
    sc_signal< sc_lv<32> > grp_fu_111_p0;
    sc_signal< sc_lv<32> > grp_fu_111_p1;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_lv<32> > grp_fu_115_p0;
    sc_signal< sc_lv<32> > grp_fu_115_p1;
    sc_signal< sc_lv<9> > or_ln17_fu_139_p2;
    sc_signal< sc_lv<8> > tmp_31_fu_162_p4;
    sc_signal< sc_lv<23> > trunc_ln31_fu_158_p1;
    sc_signal< sc_lv<1> > icmp_ln24_3_fu_178_p2;
    sc_signal< sc_lv<1> > icmp_ln24_2_fu_172_p2;
    sc_signal< sc_lv<32> > p_Result_s_fu_190_p3;
    sc_signal< sc_lv<32> > p_Val2_13_fu_203_p1;
    sc_signal< sc_lv<31> > trunc_ln368_5_fu_207_p1;
    sc_signal< sc_lv<32> > p_Result_10_fu_215_p3;
    sc_signal< sc_lv<32> > p_Val2_14_fu_228_p1;
    sc_signal< sc_lv<31> > trunc_ln368_6_fu_232_p1;
    sc_signal< sc_lv<32> > p_Result_11_fu_240_p3;
    sc_signal< sc_lv<8> > tmp_30_fu_253_p4;
    sc_signal< sc_lv<23> > trunc_ln24_fu_211_p1;
    sc_signal< sc_lv<1> > icmp_ln24_1_fu_269_p2;
    sc_signal< sc_lv<1> > icmp_ln24_fu_263_p2;
    sc_signal< sc_lv<8> > tmp_35_fu_281_p4;
    sc_signal< sc_lv<23> > trunc_ln31_1_fu_236_p1;
    sc_signal< sc_lv<1> > icmp_ln31_1_fu_297_p2;
    sc_signal< sc_lv<1> > icmp_ln31_fu_291_p2;
    sc_signal< sc_lv<1> > and_ln24_fu_309_p2;
    sc_signal< sc_lv<1> > and_ln31_fu_319_p2;
    sc_signal< sc_lv<9> > or_ln18_fu_329_p2;
    sc_signal< sc_lv<32> > p_Result_9_fu_347_p3;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<32> > bitcast_ln28_fu_364_p1;
    sc_signal< sc_lv<32> > xor_ln28_fu_368_p2;
    sc_signal< sc_lv<1> > and_ln28_fu_360_p2;
    sc_signal< sc_lv<1> > xor_ln24_fu_378_p2;
    sc_signal< sc_lv<1> > and_ln28_1_fu_383_p2;
    sc_signal< sc_lv<32> > bitcast_ln28_1_fu_374_p1;
    sc_signal< sc_lv<32> > select_ln28_fu_389_p3;
    sc_signal< sc_lv<32> > bitcast_ln35_fu_407_p1;
    sc_signal< sc_lv<32> > xor_ln35_fu_411_p2;
    sc_signal< sc_lv<1> > and_ln35_fu_403_p2;
    sc_signal< sc_lv<1> > xor_ln31_fu_421_p2;
    sc_signal< sc_lv<1> > and_ln35_1_fu_426_p2;
    sc_signal< sc_lv<32> > bitcast_ln35_1_fu_417_p1;
    sc_signal< sc_lv<32> > select_ln35_fu_432_p3;
    sc_signal< sc_lv<32> > dst_l_fu_397_p3;
    sc_signal< sc_lv<32> > dst_r_fu_440_p3;
    sc_signal< sc_lv<2> > grp_fu_95_opcode;
    sc_signal< sc_lv<2> > grp_fu_99_opcode;
    sc_signal< sc_lv<23> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<23> ap_ST_fsm_state1;
    static const sc_lv<23> ap_ST_fsm_state2;
    static const sc_lv<23> ap_ST_fsm_state3;
    static const sc_lv<23> ap_ST_fsm_state4;
    static const sc_lv<23> ap_ST_fsm_state5;
    static const sc_lv<23> ap_ST_fsm_state6;
    static const sc_lv<23> ap_ST_fsm_state7;
    static const sc_lv<23> ap_ST_fsm_state8;
    static const sc_lv<23> ap_ST_fsm_state9;
    static const sc_lv<23> ap_ST_fsm_state10;
    static const sc_lv<23> ap_ST_fsm_state11;
    static const sc_lv<23> ap_ST_fsm_state12;
    static const sc_lv<23> ap_ST_fsm_state13;
    static const sc_lv<23> ap_ST_fsm_state14;
    static const sc_lv<23> ap_ST_fsm_state15;
    static const sc_lv<23> ap_ST_fsm_state16;
    static const sc_lv<23> ap_ST_fsm_state17;
    static const sc_lv<23> ap_ST_fsm_state18;
    static const sc_lv<23> ap_ST_fsm_state19;
    static const sc_lv<23> ap_ST_fsm_state20;
    static const sc_lv<23> ap_ST_fsm_state21;
    static const sc_lv<23> ap_ST_fsm_state22;
    static const sc_lv<23> ap_ST_fsm_state23;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<55> ap_const_lv55_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<9> ap_const_lv9_2;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_80000000;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_4;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_absL_fu_223_p1();
    void thread_absR_fu_248_p1();
    void thread_and_ln24_1_fu_313_p2();
    void thread_and_ln24_fu_309_p2();
    void thread_and_ln28_1_fu_383_p2();
    void thread_and_ln28_fu_360_p2();
    void thread_and_ln31_1_fu_323_p2();
    void thread_and_ln31_fu_319_p2();
    void thread_and_ln35_1_fu_426_p2();
    void thread_and_ln35_fu_403_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_bitcast_ln28_1_fu_374_p1();
    void thread_bitcast_ln28_fu_364_p1();
    void thread_bitcast_ln35_1_fu_417_p1();
    void thread_bitcast_ln35_fu_407_p1();
    void thread_config_r_address0();
    void thread_config_r_ce0();
    void thread_dst_l_fu_397_p3();
    void thread_dst_r_fu_440_p3();
    void thread_grp_fu_111_p0();
    void thread_grp_fu_111_p1();
    void thread_grp_fu_115_p0();
    void thread_grp_fu_115_p1();
    void thread_grp_fu_95_opcode();
    void thread_grp_fu_95_p0();
    void thread_grp_fu_95_p1();
    void thread_grp_fu_99_opcode();
    void thread_grp_fu_99_p0();
    void thread_grp_fu_99_p1();
    void thread_icmp_ln24_1_fu_269_p2();
    void thread_icmp_ln24_2_fu_172_p2();
    void thread_icmp_ln24_3_fu_178_p2();
    void thread_icmp_ln24_fu_263_p2();
    void thread_icmp_ln31_1_fu_297_p2();
    void thread_icmp_ln31_fu_291_p2();
    void thread_or_ln17_fu_139_p2();
    void thread_or_ln18_fu_329_p2();
    void thread_or_ln24_1_fu_184_p2();
    void thread_or_ln24_fu_275_p2();
    void thread_or_ln31_fu_303_p2();
    void thread_p_Result_10_fu_215_p3();
    void thread_p_Result_11_fu_240_p3();
    void thread_p_Result_9_fu_347_p3();
    void thread_p_Result_s_fu_190_p3();
    void thread_p_Val2_13_fu_203_p1();
    void thread_p_Val2_14_fu_228_p1();
    void thread_ratio_fu_354_p1();
    void thread_select_ln28_fu_389_p3();
    void thread_select_ln35_fu_432_p3();
    void thread_thresh_fu_197_p1();
    void thread_tmp_30_fu_253_p4();
    void thread_tmp_31_fu_162_p4();
    void thread_tmp_35_fu_281_p4();
    void thread_tmp_43_fu_131_p3();
    void thread_tmp_44_fu_145_p3();
    void thread_tmp_45_fu_334_p3();
    void thread_trunc_ln24_fu_211_p1();
    void thread_trunc_ln31_1_fu_236_p1();
    void thread_trunc_ln31_fu_158_p1();
    void thread_trunc_ln368_4_fu_343_p1();
    void thread_trunc_ln368_5_fu_207_p1();
    void thread_trunc_ln368_6_fu_232_p1();
    void thread_trunc_ln368_fu_154_p1();
    void thread_xor_ln24_fu_378_p2();
    void thread_xor_ln28_fu_368_p2();
    void thread_xor_ln31_fu_421_p2();
    void thread_xor_ln35_fu_411_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
